// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "model": string;
      "maxTokens": number;
      "temperature": string;
      "systemPrompt": string;
      "uploadRawPdfOnFailure": boolean;
      "useMineruOnExtractFailure": boolean;
      "mineruApiToken": string;
      "reasoningEffort": string;
      "panelMode": string;
      "floatingWindowWidth": number;
      "floatingWindowHeight": number;
      "debugContextExportEnabled": boolean;
      "firstInstalledVersion": string;
      "guideStatus": number;
      "contextMaxRecentPairs": number;
      "contextEnableSummary": boolean;
      "contextAutoCompactBufferTokens": number;
      "contextAutoCompactWindowTokens": number;
      "toolPermissionDefaultModes": string;
      "webSearchProvider": string;
      "agentMaxPlanningIterations": number;
      "quickActions": string;
    };
  }
}
